# Masa Testnet Node v1.0

version: "3.6"
x-masa-testnet-node-v10-def:
  &masa-testnet-node-v10-def
  restart: "on-failure"
  image: "${MASA_DOCKER_IMAGE:-quorumengineering/quorum:22.1}"
  expose:
    - "21000"
    - "50400"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  labels:
    com.masa.consensus: ${MASA_CONSENSUS:-istanbul}
  entrypoint:
    - /bin/sh
    - -c
    - |
      DDIR=/qdata/dd
      GENESIS_FILE="/network/genesis.json"
      CONSENSUS_RPC_API="istanbul"
      NETWORK_ID=$$(cat $${GENESIS_FILE} | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
      GETH_ARGS_istanbul="--emitcheckpoints --istanbul.blockperiod 10 --mine --miner.threads 1 --syncmode full"
      if [ ! -f $${DDIR}/control_file ]; then
        mkdir -p $${DDIR}/keystore
        mkdir -p $${DDIR}/geth
        geth --datadir $${DDIR} init $${GENESIS_FILE}
        echo "Created $$(date)" > $${DDIR}/control_file
      fi
      geth \
        --identity ${NODE_ID} \
        --datadir $${DDIR} \
        --bootnodes enode://91a3c3d5e76b0acf05d9abddee959f1bcbc7c91537d2629288a9edd7a3df90acaa46ffba0e0e5d49a20598e0960ac458d76eb8fa92a1d64938c0a3a3d60f8be4@54.158.188.182:21000,enode://ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef@54.146.254.245:21000,enode://91a3c3d5e76b0acf05d9abddee959f1bcbc7c91537d2629288a9edd7a3df90acaa46ffba0e0e5d49a20598e0960ac458d76eb8fa92a1d64938c0a3a3d60f8be4@54.158.188.182:21000,enode://d87c03855093a39dced2af54d39b827e4e841fd0ca98673b2e94681d9d52d2f1b6a6d42754da86fa8f53d8105896fda44f3012be0ceb6342e114b0f01456924c@34.225.220.240:21000,enode://fcb5a1a8d65eb167cd3030ca9ae35aa8e290b9add3eb46481d0fbd1eb10065aeea40059f48314c88816aab2af9303e193becc511b1035c9fd8dbe97d21f913b9@52.1.125.71:21000        --verbosity 5 \
        --networkid $${NETWORK_ID} \
        --http \
        --http.corsdomain "*" \
        --http.vhosts "*" \
        --http.addr 0.0.0.0 \
        --http.port 8545 \
        --http.api admin,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$${CONSENSUS_RPC_API} \
        --port 21000 \
        --nousb \
        ${MASA_GETH_ARGS:-} $${GETH_ARGS_${MASA_CONSENSUS:-istanbul}}
services:
  ui:
    image: masafinance/node-ui
    ports:
      - 3000:3000
  masa-node:
    << : *masa-testnet-node-v10-def
    hostname: masa-node
    ports:
      - "22001:8545"
    volumes:
      - vol1:/qdata
      - ./network/testnet:/network:ro
    environment:
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/qdata/tm/tm.ipc}
      - NODE_ID=1
    networks:
      masa-testnet:
        ipv4_address: 172.16.240.20
networks:
  masa-testnet:
    name: masa-testnet
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.240.0/24
volumes:
  "vol1":
